[env]
RUST_LOG="debug"  # 默认
CARGO_CONFIG_DIR=".cargo/"

[run]
env = { RUST_LOG="debug" }  # 仅对 `cargo run` 生效

[test]
env = { RUST_LOG = "trace" }  # 仅对 `cargo test` 生效

# DB
SERVICE_DB_URL="postgres://app_user:dev_only_pwd@124.222.48.193/app_db"
SERVICE_PWD_KEY="CKUGFOD9_2Qf6Pn3ZFRYgPYb8ht4vKqEG9PGMXTB7497bT0367DjoaD6ydFnEVaIRda0kKeBZVCT5Hb62m2sCA"
SERVICE_TOKEN_KEY="9FoHBmkyxbgu_xFoQK7e0jz3RMNVJWgfvbVn712FBNH9LLaAWS3CS6Zpcg6RveiObvCUb6a2z-uAiLjhLh2igw"
SERVICE_TOKEN_DURATION_SEC="1800" # 30 minutes

# Web Folder
SERVICE_WEB_FOLDER="web-folder/"

#[target.x86_64-pc-windows-msvc]
#linker = "C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/link.exe"
#