// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!

export type { History } from "/Users/simonwang/Documents/others/docs/react/node_modules/@umijs/renderer-react";
// @umijs/renderer-*
export {
  __getRoot,
  __useFetcher,
  createBrowserHistory,
  createHashHistory,
  createMemoryHistory,
  createSearchParams,
  generatePath,
  Helmet,
  HelmetProvider,
  Link,
  matchPath,
  matchRoutes,
  Navigate,
  NavLink,
  Outlet,
  renderClient,
  resolvePath,
  useAppData,
  useClientLoaderData,
  useLocation,
  useMatch,
  useNavigate,
  useOutlet,
  useOutletContext,
  useParams,
  useResolvedPath,
  useRouteData,
  useRouteProps,
  useRoutes,
  useSearchParams,
  useSelectedRoutes,
  useServerLoaderData,
  withRouter,
} from "/Users/simonwang/Documents/others/docs/react/node_modules/@umijs/renderer-react";
// umi/client/client/plugin
export {
  ApplyPluginsType,
  PluginManager,
} from "/Users/simonwang/Documents/others/docs/react/node_modules/umi/client/client/plugin.js";
export type { RuntimeConfig } from "./core/defineApp";
export { defineApp } from "./core/defineApp";
export { createHistory, history } from "./core/history";
export { terminal } from "./core/terminal";
export { TestBrowser } from "./testBrowser";
export const useServerInsertedHTML: Function = () => {};
// plugins
// plugins types.d.ts
